"""
Django settings for mysite3base project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

# Twitter Boostrap3 Messages
from django.contrib import messages

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = True

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale.
USE_L10N = True

# If you set this to False, Django will not use timezone-aware datetimes.
USE_TZ = True

#Aliyun OSS
STATICFILES_STORAGE = 'aliyun_oss_custom.aliyun_oss_custom.StaticStorage'
DEFAULT_FILE_STORAGE = 'aliyunstorage.backends.AliyunOssStorage'
THUMBNAIL_DEFAULT_STORAGE = 'aliyunstorage.backends.AliyunOssStorage'

ALIYUN_OSS_KEY_ID = "OOH5rOr11Q1c9oJA"
ALIYUN_OSS_KEY_SECRET = os.environ['ALIYUN_OSS_KEY_SECRET']  # your aliyun access key id & scret
ALIYUN_OSS_END_POINT = "oss-cn-shenzhen.aliyuncs.com" #your aliyun oss endpoint
#ALIYUN_OSS_END_POINT = "oss-cn-shenzhen-internal.aliyuncs.com"
ALIYUN_OSS_BUCKET_NAME = "enlingo"  # your bucket name
OSS_TIMEOUT ="3600" # oss access timeout, default as 30s.
ALIYUN_OSS_CUSTOM_DOMAIN = '%s.%s' % (ALIYUN_OSS_BUCKET_NAME, ALIYUN_OSS_END_POINT)

# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/home/media/media.lawrence.com/media/"
MEDIA_ROOT = "site_media/media/"

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://media.lawrence.com/media/", "http://example.com/media/"
# MEDIA_URL = "//static.qsvisa.com/"
MEDIA_URL = "//%s/" % (ALIYUN_OSS_CUSTOM_DOMAIN)

# Absolute path to the directory static files should be collected to.
# Don"t put anything in this directory yourself; store your static files
# in apps" "static/" subdirectories and in STATICFILES_DIRS.
# Example: "/home/media/media.lawrence.com/static/"
STATIC_ROOT = "site_media/static/"

# URL prefix for static files.
# Example: "http://media.lawrence.com/static/"
STATIC_URL = "//%s/%s/" % (ALIYUN_OSS_CUSTOM_DOMAIN, 'site_media/static')

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static", "dist"),
]

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Application definition

INSTALLED_APPS = (
    'bootstrap3',
    'django_admin_bootstrapped',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'localflavor',
    'django_countries',
    'django.contrib.humanize',

    #Pinax Account
    'pinax_theme_bootstrap',
    'bootstrapform',
    'account',
    'metron',

    #Pinax Blogs
    "pinax.blog",

    #Enlingo Processes
    'coursesearch',
    'consultantregistration',
    'studentapply',

    #haystack search
    'haystack',

    #elasticsearch
    'elasticsearch',

    #roles
    'roles',

    #Workflow
    'viewflow',
    #'djcelery',

    #Cripsy Forms
    'crispy_forms',

    #django tables2
    'django_tables2',

    #Analytical
    'analytical',

    #django-formtools
    'formtools',

    #memberuserpanel
    'userpanel',

    #Pinax Stripe
    'pinax.stripe',

    #Django Guardian
    'guardian',

    #Enlingo memberpackage
    'memberpackage',

    #Pinax Invitations
    'pinax.invitations',
    #'eldarion.ajax',

    #Django Filer
    'easy_thumbnails',
    'filer',
    'mptt',

    #Aliyun Storage
    'aliyunstorage',
    'aliyun_oss_custom',

    #ckeditor
    'ckeditor',
    'ckeditor_uploader',

    #django-newsletter
    'django_extensions',
    'sorl.thumbnail',
    'newsletter',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'account.middleware.LocaleMiddleware',
    'account.middleware.TimezoneMiddleware',
)

ROOT_URLCONF = 'mysite4base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'account.context_processors.account',
                'django.core.context_processors.request',
                'django.core.context_processors.i18n',
                'pinax_theme_bootstrap.context_processors.theme',
            ],
        },
    },
]
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# AWS

AWS_ACCESS_KEY_ID = 'AKIAIXAU6CD6KL4SOKLA'
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
AWS_SES_REGION_HOME = 'us-west-2'
AWS_SES_REGION_ENDPOINT = 'email.us-west-2.amazonaws.com'
#AWS_SES_ACCESS_KEY_ID = 'AKIAIXAU6CD6KL4SOKLA'
#AWS_SES_SECRET_ACCESS_KEY = os.environ['AWS_SES_SECRET_ACCESS_KEY']

#Emailbackend settings
#EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django_ses.SESBackend'
DEFAULT_FROM_EMAIL = "member.support@enlingo.com"
SERVER_EMAIL="hbzz.hwb@163.com"

#account module settings
ACCOUNT_OPEN_SIGNUP = True
ACCOUNT_EMAIL_UNIQUE = True
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = True
ACCOUNT_LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 2
ACCOUNT_USE_AUTH_AUTHENTICATE = True

AUTHENTICATION_BACKENDS = [
#   "account.auth_backends.UsernameAuthenticationBackend",
   "account.auth_backends.EmailAuthenticationBackend",
    'django.contrib.auth.backends.ModelBackend', # default
    "guardian.backends.ObjectPermissionBackend",
]
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

#boostrap3 render

DAB_FIELD_RENDERER = 'django_admin_bootstrapped.renderers.BootstrapFieldRenderer'

# Twitter Boostrap3 Messages
MESSAGE_TAGS = {
    messages.SUCCESS: 'alert-success success',
    messages.WARNING: 'alert-warning warning',
    messages.ERROR: 'alert-danger error'
}

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
        'URL': 'http://127.0.0.1:9200',
        'INDEX_NAME': 'haystack',
    },
}

# SITE_ID for django.contrib.sites, deprecated for enlingo.com as using two wsgi.py modules to represent two subdomains: enlingo.com - student_settings
# member.enlingo.com - member_settings

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    #'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)

#ckeditor settings
CKEDITOR_JQUERY_URL = 'ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_UPLOAD_PATH = "uploads/"

#Django-newsletter settings
NEWSLETTER_CONFIRM_EMAIL = False
NEWSLETTER_RICHTEXT_WIDGET = 'ckeditor.widgets.CKEditorWidget'